# TCL File Generated by Component Editor 9.0sp2
# Mon Jun 29 20:43:35 PDT 2009
# DO NOT MODIFY


# +-----------------------------------
# | 
# | lcd_driver "lcd_driver" v1.0
# | null 2009.06.29.20:43:35
# | 
# | 
# | E:/work/f51852_top/lcd_driver.vhd
# | 
# |    ./lcd_driver.vhd syn, sim
# | 
# +-----------------------------------


# +-----------------------------------
# | module lcd_driver
# | 
set_module_property NAME lcd_driver
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP "CycloneIII Host Development Kit/Peripherals/Display"
set_module_property DISPLAY_NAME lcd_driver
set_module_property LIBRARIES {ieee.std_logic_1164.all ieee.std_logic_arith.all ieee.std_logic_unsigned.all std.standard.all}
set_module_property TOP_LEVEL_HDL_FILE lcd_driver.vhd
set_module_property TOP_LEVEL_HDL_MODULE lcd_driver
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file lcd_driver.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment DYNAMIC
set_interface_property avalon_slave_0 bridgesToMaster ""
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ASSOCIATED_CLOCK clock_sink
set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 nios_s_data_in writedata Input 32
add_interface_port avalon_slave_0 nios_s_data_out readdata Output 32
add_interface_port avalon_slave_0 nios_s_address address Input 3
add_interface_port avalon_slave_0 nios_s_chipselect_n chipselect_n Input 1
add_interface_port avalon_slave_0 nios_s_write_n write_n Input 1
add_interface_port avalon_slave_0 nios_s_read_n read_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink
# | 
add_interface clock_sink clock end
set_interface_property clock_sink ptfSchematicName ""

set_interface_property clock_sink ENABLED true

add_interface_port clock_sink nios_clk clk Input 1
add_interface_port clock_sink nios_reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_read_master
# | 
add_interface avalon_read_master avalon start
set_interface_property avalon_read_master adaptsTo ""
set_interface_property avalon_read_master burstOnBurstBoundariesOnly false
set_interface_property avalon_read_master doStreamReads false
set_interface_property avalon_read_master doStreamWrites false
set_interface_property avalon_read_master linewrapBursts false

set_interface_property avalon_read_master ASSOCIATED_CLOCK clock_sink
set_interface_property avalon_read_master ENABLED true

add_interface_port avalon_read_master nios_r_data_in readdata Input 32
add_interface_port avalon_read_master nios_r_chipselect_n chipselect_n Output 1
add_interface_port avalon_read_master nios_r_read_n read_n Output 1
add_interface_port avalon_read_master nios_r_waitrequest waitrequest_n Input 1
add_interface_port avalon_read_master nios_r_address address Output 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end lcd_en export Output 1
add_interface_port conduit_end lcd_rstn export Output 1
add_interface_port conduit_end lcd_csn export Output 1
add_interface_port conduit_end lcd_d_cn export Output 1
add_interface_port conduit_end lcd_wen export Output 1
add_interface_port conduit_end lcd_e_rdn export Output 1
add_interface_port conduit_end lcd_data export Bidir 8
# | 
# +-----------------------------------
