# Caution: this file may be regenerated by SOPC Builder.  User edits will be lost.
project_open -current_revision "C:/altera/80/kits/cycloneIII_3c120_dev/examples/cycloneIII_3c120_dev_niosII_standard/cycloneIII_3c120_dev_niosII_standard.qpf"
project_close