# TCL File Generated by Component Editor 9.0sp2
# Thu Oct 08 17:05:29 PDT 2009
# DO NOT MODIFY


# +-----------------------------------
# | 
# | sseg_controller "sseg_controller" v1.0
# | null 2009.10.08.17:05:29
# | 
# | 
# | C:/kei/s4e/bts_config/sseg_controller.vhd
# | 
# |    ./sseg_controller.vhd syn, sim
# | 
# +-----------------------------------


# +-----------------------------------
# | module sseg_controller
# | 
set_module_property NAME sseg_controller
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP "CycloneIII Host Development Kit/Peripherals/Display"
set_module_property DISPLAY_NAME sseg_controller
set_module_property LIBRARIES {ieee.std_logic_1164.all std.standard.all}
set_module_property TOP_LEVEL_HDL_FILE sseg_controller.vhd
set_module_property TOP_LEVEL_HDL_MODULE sseg_controller
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file sseg_controller.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment DYNAMIC
set_interface_property avalon_slave_0 bridgesToMaster ""
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ASSOCIATED_CLOCK clock_sink
set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 nios_s_data_in writedata Input 32
add_interface_port avalon_slave_0 nios_s_data_out readdata Output 32
add_interface_port avalon_slave_0 nios_s_address address Input 3
add_interface_port avalon_slave_0 nios_s_chipselect_n chipselect_n Input 1
add_interface_port avalon_slave_0 nios_s_write_n write_n Input 1
add_interface_port avalon_slave_0 nios_s_read_n read_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink
# | 
add_interface clock_sink clock end
set_interface_property clock_sink ptfSchematicName ""

set_interface_property clock_sink ENABLED true

add_interface_port clock_sink nios_clk clk Input 1
add_interface_port clock_sink nios_reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ENABLED true

add_interface_port conduit_end ss_data export Output 7
add_interface_port conduit_end ss_sel export Output 4
# | 
# +-----------------------------------
