# TCL File Generated by Component Editor 9.1
# Fri Nov 06 11:03:48 PST 2009
# DO NOT MODIFY


# +-----------------------------------
# | 
# | ssram16 "ssram16" v1.0
# | me 2009.11.06.11:03:48
# | test
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 9.1
# | 
package require -exact sopc 9.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module ssram16
# | 
set_module_property DESCRIPTION test
set_module_property NAME ssram32
set_module_property VERSION 9.1
set_module_property INTERNAL false
set_module_property GROUP "CycloneIII Host Development Kit/Memories and Memory Controllers/SRAM"
set_module_property AUTHOR me
set_module_property DISPLAY_NAME ssram32
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end

set_interface_property clock ENABLED true

add_interface_port clock ssram_clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point export_0
# | 
add_interface export_0 conduit end

set_interface_property export_0 ASSOCIATED_CLOCK clock
set_interface_property export_0 ENABLED true
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_tristate_slave
# | 
add_interface avalon_tristate_slave avalon_tristate end
set_interface_property avalon_tristate_slave activeCSThroughReadLatency false
set_interface_property avalon_tristate_slave explicitAddressSpan 0
set_interface_property avalon_tristate_slave holdTime 200
set_interface_property avalon_tristate_slave isMemoryDevice true
set_interface_property avalon_tristate_slave isNonVolatileStorage false
set_interface_property avalon_tristate_slave maximumPendingReadTransactions 0
set_interface_property avalon_tristate_slave printableDevice false
set_interface_property avalon_tristate_slave readLatency 2
set_interface_property avalon_tristate_slave readWaitStates 200
set_interface_property avalon_tristate_slave readWaitTime 200
set_interface_property avalon_tristate_slave setupTime 200
set_interface_property avalon_tristate_slave timingUnits Nanoseconds
set_interface_property avalon_tristate_slave writeWaitStates 200
set_interface_property avalon_tristate_slave writeWaitTime 200

set_interface_property avalon_tristate_slave ASSOCIATED_CLOCK clock
set_interface_property avalon_tristate_slave ENABLED true

add_interface_port avalon_tristate_slave ssram_data data Bidir 32
add_interface_port avalon_tristate_slave ssram_oen read_n Input 1
add_interface_port avalon_tristate_slave ssram_cen chipselect_n Input 1
add_interface_port avalon_tristate_slave ssram_wen write_n Input 1
add_interface_port avalon_tristate_slave ssram_bwn byteenable_n Input 4
add_interface_port avalon_tristate_slave ssram_address address Input 21
# | 
# +-----------------------------------
