# TCL File Generated by Component Editor 9.1sp2
# Thu May 06 15:00:34 SGT 2010
# DO NOT MODIFY


# +-----------------------------------
# | 
# | nios_bts_port_ddr2_x32 "nios_bts_port_ddr2_x32" v1.0
# | Altera 2010.05.06.15:00:34
# | 
# | 
# | D:/_Netbean/cyclone3_3c120_dev/bts_ddr2_f_c3ls/bts_ddr2/nios_bts_port_ddr2_x64_b7.v
# | 
# |    ./nios_bts_port_ddr2_x32.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 9.1
# | 
package require -exact sopc 9.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module nios_bts_port_ddr2_x32
# | 
set_module_property DESCRIPTION ""
set_module_property NAME nios_bts_port_ddr2_x32
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP "NIOS BTS"
set_module_property AUTHOR Altera
set_module_property DISPLAY_NAME nios_bts_port_ddr2_x32
set_module_property TOP_LEVEL_HDL_FILE nios_bts_port_ddr2_x32.v
set_module_property TOP_LEVEL_HDL_MODULE nios_bts_port_ddr2_x32
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file nios_bts_port_ddr2_x32.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset nios_reset_n reset_n Input 1
add_interface_port clock_reset nios_clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ASSOCIATED_CLOCK clock_reset
set_interface_property conduit_end ENABLED true

add_interface_port conduit_end start_pb export Input 1
add_interface_port conduit_end create_error_pb export Input 1
add_interface_port conduit_end plls_in_locked export Input 1
add_interface_port conduit_end plls_locked export Output 1
add_interface_port conduit_end pattern_sync_acquired export Output 1
add_interface_port conduit_end test_complete export Output 1
add_interface_port conduit_end error_latch export Output 1
add_interface_port conduit_end avalon_pb export Input 8
add_interface_port conduit_end avalon_dip export Input 8
add_interface_port conduit_end avalon_led export Output 8
add_interface_port conduit_end local_clk export Input 1
add_interface_port conduit_end local_addr export Output 23
add_interface_port conduit_end local_be export Output 16
add_interface_port conduit_end local_init_done export Input 1
add_interface_port conduit_end local_rdata export Input 128
add_interface_port conduit_end local_rdata_valid export Input 1
add_interface_port conduit_end local_rdvalid_in_n export Input 1
add_interface_port conduit_end local_read_req export Output 1
add_interface_port conduit_end local_ready export Input 1
add_interface_port conduit_end local_size export Output 1
add_interface_port conduit_end local_burst_begin export Output 1
add_interface_port conduit_end local_wdata export Output 128
add_interface_port conduit_end local_wdata_req export Input 1
add_interface_port conduit_end local_write_req export Output 1
add_interface_port conduit_end local_reset_n export Output 1
add_interface_port conduit_end reset_n export Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point nios
# | 
add_interface nios avalon end
set_interface_property nios addressAlignment DYNAMIC
set_interface_property nios associatedClock clock_reset
set_interface_property nios burstOnBurstBoundariesOnly false
set_interface_property nios explicitAddressSpan 0
set_interface_property nios holdTime 0
set_interface_property nios isMemoryDevice false
set_interface_property nios isNonVolatileStorage false
set_interface_property nios linewrapBursts false
set_interface_property nios maximumPendingReadTransactions 0
set_interface_property nios printableDevice false
set_interface_property nios readLatency 0
set_interface_property nios readWaitTime 1
set_interface_property nios setupTime 0
set_interface_property nios timingUnits Cycles
set_interface_property nios writeWaitTime 0

set_interface_property nios ASSOCIATED_CLOCK clock_reset
set_interface_property nios ENABLED true

add_interface_port nios nios_address address Input 20
add_interface_port nios nios_chipselect chipselect Input 1
add_interface_port nios nios_read read Input 1
add_interface_port nios nios_readdata readdata Output 32
add_interface_port nios nios_write write Input 1
add_interface_port nios nios_writedata writedata Input 32
add_interface_port nios nios_waitrequest waitrequest Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point interrupt_sender
# | 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint nios

set_interface_property interrupt_sender ASSOCIATED_CLOCK clock_reset
set_interface_property interrupt_sender ENABLED true

add_interface_port interrupt_sender error_irq irq Output 1
# | 
# +-----------------------------------
